const ServiceStatus = {
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVED: 'APPROVED',
  AGENT_ASSIGNED: 'AGENT_ASSIGNED'
};

const ServiceProgress = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED'
};

const ServiceType = {
  CASH_DEPOSIT: 'CASH_DEPOSIT',
  CASH_WITHDRAWAL: 'CASH_WITHDRAWAL',
  DOCUMENT_COLLECTION: 'DOCUMENT_COLLECTION',
  DOCUMENT_DELIVERY: 'DOCUMENT_DELIVERY',
  ONLINE_ASSISTANCE: 'ONLINE_ASSISTANCE',
  LIFE_CERTIFICATE: 'LIFE_CERTIFICATE',
  NEW_ACCOUNT: 'NEW_ACCOUNT'
};

module.exports = { ServiceStatus, ServiceProgress, ServiceType };